name: appwrite_graphql_client
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  copy_with_extension: ^4.0.0
  country_icons: ^2.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_speed_dial: ^5.0.0+1
  graphql: ^5.0.1
  intl: ^0.17.0
  json_annotation: ^4.4.0
  rxdart: ^0.27.3

dev_dependencies:
  build_runner: ^2.1.8
  copy_with_extension_gen: ^4.0.1
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/medals/
