name: code_connect_frontend
description: Code Connect client side application.
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  code_connect_common:
    path: ../common
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_mobx: ^2.2.0+2
  mobx: ^2.3.0+1
  rust_core: ^0.4.0
  url_launcher: ^6.2.5

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.6.0+1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
