name: code_connect
description: Code Connect streamlines connecting software engineers with new project ideas.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.3.0

dev_dependencies:
  flutter_lints: ^3.0.1
