name: Publish new release to GitHub

on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  run-tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Swift
        uses: SwiftyLab/setup-swift@latest

      - name: Run tests
        run: swift test --enable-experimental-swift-testing

  build-and-upload:
    needs: run-tests
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            platform: linux
          - os: macos-13
            platform: macos
          - os: windows-latest
            platform: windows
            binary-suffix: .exe

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Swift
        uses: SwiftyLab/setup-swift@latest

      - name: Build release binary
        run: swift build -c release

      - name: Rename binary
        id: rename-binary
        shell: bash
        run: |
          SOURCE="GitBranchCleaner${{ matrix.binary-suffix }}"
          TARGET="gbc-${{ github.ref_name }}-${{ matrix.platform }}${{ matrix.binary-suffix }}"
          cp ".build/release/$SOURCE" ".build/$TARGET"
          if [[ "${{ matrix.platform }}" != "windows" ]]; then
            chmod +x ".build/$TARGET"
          fi
          echo "target=$TARGET" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.rename-binary.outputs.target }}
          path: .build/${{ steps.rename-binary.outputs.target }}
          if-no-files-found: error

  create-release:
    needs: build-and-upload
    runs-on: ubuntu-22.04
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            gbc-${{ github.ref_name }}-*
