name: Run tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Swift
        uses: SwiftyLab/setup-swift@latest

      - name: Run tests
        run: swift test --enable-experimental-swift-testing
